### ISSUE TITLE
Deployment fails then get stuck on "Invoking deployment process"

### ISSUE THREAD

**Issue by Xample** [fabienb4/meteor-up#1]
Hi I tried to make a simple app (meteor create myApp) and tried to deploy on my server (meteor v1.1). (The deployment was working in the past with the 1.0.4 node 0.10.35)
- I removed completely the deployed app from the server (/opt/myApp)
- deb-mup setup
- deb-mup deploy

The first time I deploy I eventually get the following error:

``` console
[copecode.net] - Uploading bundle
[copecode.net] ✔ Uploading bundle: SUCCESS
[copecode.net] - Setting up Environment Variables
[copecode.net] ✔ Setting up Environment Variables: SUCCESS
[copecode.net] - Invoking deployment process
[copecode.net] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'XXXX,XXX' (RSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.5 install /opt/wow/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@4.1.0 node_modules/semver

    fibers@1.0.5 node_modules/fibers

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── escape-string-regexp@1.0.3
    ├── supports-color@0.2.0
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Stopping wow meteor instance
    Starting wow meteor instance
    Waiting for 120 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
```

If I try to deploy once again right after, I just get stuck on the "Invoking deployment process" phase.

**Comment by fabienb4** [comment]
Meteor 1.0.4 uses node 0.10.36 (see [Meteor history](https://github.com/meteor/meteor/blob/devel/History.md#other-bug-fixes-and-improvements-1)). You need to update your config file so that node 0.10.36 gets installed on your server (`mup.json`):

``` javascript
  "setupNode": true,
  "nodeVersion": "0.10.36",
```

Also update deb-mup, I just released v0.9.7 which fixes an error from arunoda/meteor-up.

I just deployed an app (1.1) on my server, it worked perfectly.

**Comment by Xample** [comment]
I already updated the node dependency and took the last version of deb-mup (deb-mup@0.9.7), but it did not solved the problem. The problem is somewhere else, the deployment seems to be fine but the script is unable to launch the init.d service. I have to manually start the app service.
Launching the app with

``` bash
DEBUG=* deb-mup deploy
```

The script get stuck there:

``` console
# chown to support dumping heapdump and etc
sudo chown -R meteoruser app
 +8ms
  nodemiral:sess:copecode.net spawning command- ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /tmp/TDfqr222IRTzrLZHt user@myhost.net "bash -s" < /tmp/DGYTL6p8fu7K5C0bY +1ms
```

Any clue ?

**Comment by Xample** [comment]
Ok I fixed the problem, for some reason

``` json
  "setupNode": true,
  "nodeVersion": "0.10.36",
```

Did **NOT** updated my node version

I therefore ran manually the following commands:

``` bash
sudo npm install -g n
sudo n 0.10.36
```

``` bash
node -v
v0.10.36
```

**Comment by fabienb4** [comment]
Interesting problem. I just did it a few days ago, and it updated my version of node correctly.

Was your first node install done using deb-mup/mup?

**Comment by Xample** [comment]
No I manually installed it first, the same with mongodb, before you made the deb-mup it was a real pain to deploy on my server using mup.
By the way, I cannot install mongodb through the script neither, I always get a problem like a real bash is needed for displaying the installation console (something like this)

I should try another install on a fresh debian install for a customer in the next weeks. I will keep you in touch if I encounter any trouble at this time.

Flavien

**Comment by fabienb4** [comment]
There might be a conflict with node installations. If you take a look at [node install script](https://github.com/fabienb4/meteor-up/blob/master/scripts/linux/install-node.sh#L32) it uses the binaries from nodejs.org website to install it, not the deb package from deb.nodesource.com.
Well, I'll need to further investigate the issues. But I suspect the fresh install will work without troubles.

For the bash problem:
If `/bin/sh` is a symlink to `dash`, try using (as root) `dpkg-reconfigure dash`, and answer no. I remember having some trouble with dash, with a similar error message sometime ago (different context/program though).
You can see the symlink using `ls -l /bin/sh`.

**Comment by Xample** [comment]
sure

falconx@Debian-70-wheezy-64-LAMP:~$ echo $SHELL
/bin/bash

**Comment by fabienb4** [comment]
Well, I'll need to further investigate the issues. But I suspect the fresh install will work without troubles.

For the bash problem:
If `/bin/sh` is a symlink to `dash`, try using (as root) `dpkg-reconfigure dash`, and answer no. I remember having some trouble with dash, with a similar error message sometime ago (different context/program though).
You can see the symlink using `ls -l /bin/sh`.

**Comment by Xample** [comment]
I would also trust the fresh install… it is out of subject but I am considering using perhaps Docker instead of playing with several servers/VM

Otherwise:

falconx@Debian-70-wheezy-64-LAMP:~$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Apr  2 23:25 /bin/sh -> bash

**Comment by fabienb4** [comment]
Well, you have bash, so that's no it ;-)

Keep me posted on the fresh install result.
